-- drop all tables from the last test
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS usr CASCADE;
DROP TABLE IF EXISTS chats CASCADE;

DROP TABLE IF EXISTS usr_posts_chats;
DROP TABLE IF EXISTS follow;
DROP TABLE IF EXISTS anexes;

-- Re create tables

CREATE TABLE chats(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  name VARCHAR(20) NOT NULL,
  description VARCHAR(50),

  photo_link VARCHAR(20),

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE usr (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  email VARCHAR(30) NOT NULL,
  age SMALLINT CHECK(age >= 18) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  photo_link VARCHAR(20), 

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE posts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  title VARCHAR(45) NOT NULL,
  text TEXT NOT NULL,
  likes INTEGER DEFAULT(0),

  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE follow(
  id_from INT REFERENCES usr(id),
  id_to INT REFERENCES usr(id),
  
  PRIMARY KEY(id_from, id_to)
);

CREATE TABLE usr_posts_chats(
  id_usr INT REFERENCES usr(id),
  id_post INT REFERENCES posts(id),
  id_chats INT REFERENCES chats(id), 
  PRIMARY KEY(id_usr, id_post, id_chats)
);


CREATE TABLE anexes (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  id_post INT REFERENCES posts(id) NOT NULL,
  file_link VARCHAR(50) NOT NULL,
  mime_type VARCHAR(20) NOT NULL,
  mime_subtype VARCHAR(20) NOT NULL
);



-- insert dummy data

INSERT INTO chats(
  name,
  description
)
VALUES(
  'TECNOLOGIES',
  'A chat about tech'
),
(
  'Music',
  'Discussion about music'
),
(
  'Deutsch Sprechen',
  'A sehr schön über Deutsch Sprachen'
),
(
  'Daily life',
  'A chat about daily life'
),
(
  'Travelling',
  'A chat to share your experiences around the world'
);


INSERT INTO usr (
  first_name,
  last_name,
  email,
  age,
  phone
)
VALUES (
    'Mateus Felipe',
    'Silveira Vieira Schreiner',
    '10723904@mackenzista.com',
    19,
    '11 979246-6876'
  ), 
  (
    'Rayana',
    'Pimentel',
    'ra@mackenzista.com', 
    19, 
    '11 979246-6876'
  ), 
  (
    'Cidinha', 
    'Delgado', 
    'cidinha@musica.com', 
    60, 
    '11 979248-6876'
  ), 
  ( 
    'Vitinho',
    'Roveri',
    'vitor@pianista.com',
    37, 
    '11 979236-6876'
  ), 
  ( 
    'Karen', 
    'Comanduli', 
    'pio_x@musica.com', 
    50, 
    '11 979246-6876'
  );

INSERT INTO follow(
  id_from,
  id_to
)
VALUES(1,5), (2,1), (1,2), (4,5),(4,3);


INSERT INTO posts(
  title,
  text
)
VALUES(
  'What is free (as in freedom) software',
  'Specifically, free software means users have the four essential freedoms: 
  (0) to run the program,
  (1) to study and change the program in source code form, 
  (2) to redistribute exact copies, and (3) to distribute modified versions.'
),
(
  'Why I like Linux',
  'I like linux because is free, is flexible and costumizable'
),
(
  'Best Classical Musics to Sing in a Chor',
  'There a lot of options. However Bach, Mozart and Beethoven are good choiches'
),
(
  'How theach music for children',
  'Fist is important a lot of patience and perceverance'
),
(
  'My day today',
  'I have a pretty good day today. I awakend and ...'
),
(
  'Was habe ich am letzten Donnerstag gemacht',
  'Hallo Freunde*innen, am Donnerstag bin ich nach Jundiaí gefahren und ...' 
)
;

INSERT INTO usr_posts_chats(
  id_usr,
  id_post,
  id_chats
)
VALUES(1,1,1),(1,2,1),(5,3,2),(3,4,2),(2,5,4),(1,6,4);

INSERT INTO anexes(
  id_post,
  file_link,
  mime_type,
  mime_subtype
)
VALUES(
  1,
  'https://www.gnu.org/philosophy/philosophy.html.en',
  'html',
  'hyperlink'
),
(
  1,
  'https://www.gnu.org/graphics/agplv3-155x51.png',
  'image',
  'png'
),
(
  2,
  'https://www.kernel.org/theme/images/logos/tux.png',
  'image',
  'png'
),
(
  4,
  'https://freesvg.org/img/noun_project_928.png',
  'image',
  'png'
),
(
  4,
  'imagem bem legal',
  'image',
  'png'
);

-- add like to see if works
UPDATE posts SET likes = likes + 1 WHERE id = 3;

SELECT id, name, description, created_at FROM chats;  -- chats

SELECT id, first_name, last_name, email, age, phone FROM usr; --usr

SELECT id, title, SUBSTRING(text FROM 1 FOR 13) || '...' 
AS text__init, likes, created_at FROM posts; -- posts

-- usr_posts_chats
SELECT id_usr, id_post, id_chats FROM usr_posts_chats; 

-- 3.4 3 Tabelas Inner join
SELECT SUBSTRING(posts.title FROM 1 FOR 35) || '...' AS title, SUBSTRING(text FROM 1 FOR 13) || '...' AS text,
chats.name AS chat__name, 
first_name, usr.id AS usr__id  FROM usr 
INNER JOIN usr_posts_chats ON usr.id = usr_posts_chats.id_usr
INNER JOIN posts ON posts.id = usr_posts_chats.id_post
INNER JOIN chats ON chats.id = usr_posts_chats.id_chats;

-- followers
SELECT id_from, id_to FROM follow;

SELECT usr_from.id AS id_from, follow.id_to, 
usr_from.first_name AS name_from, usr_to.first_name AS name_to FROM usr usr_from
INNER JOIN follow ON usr_from.id = follow.id_from 
INNER JOIN usr usr_to ON usr_to.id = follow.id_to;

-- anexes
SELECT id, id_post, file_link, mime_type, mime_subtype FROM anexes;

SELECT anexes.id AS anexes__id, posts.id AS post__id, SUBSTRING(posts.title FROM 1 FOR 8) || '...' AS title, 
SUBSTRING(file_link FROM 1 FOR 15) || '...' AS file_link, 
mime_type, mime_subtype FROM anexes
INNER JOIN posts ON anexes.id_post = posts.id;

/* Query Projeto 2*/

-- 3.1
SELECT COUNT(first_name) AS search_by_email FROM usr
WHERE email LIKE '%@mackenzista%';


-- 3.2
SELECT id_from, follows.first_name AS first_name_follows, COUNT(id_to) AS following FROM follow
INNER JOIN usr follows ON id_from = follows.id
GROUP BY id_from, first_name;

-- 3.3
SELECT posts.id, posts. title id_post, SUBSTRING(file_link FROM 1 FOR 13) || '...' AS file_link, mime_type, mime_subtype FROM anexes
RIGHT JOIN posts ON posts.id = anexes.id;

-- 3.4 3 Tabelas Inner join
SELECT posts.id, SUBSTRING(posts.title FROM 1 FOR 25) || '...' AS title, SUBSTRING(text FROM 1 FOR 13) || '...' AS text,
chats.name AS chat__name, 
first_name, usr.id AS usr__id  FROM usr 
INNER JOIN usr_posts_chats ON usr.id = usr_posts_chats.id_usr
INNER JOIN posts ON posts.id = usr_posts_chats.id_post
INNER JOIN chats ON chats.id = usr_posts_chats.id_chats;
